api/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.conf.urls import include, patterns, url
from rest_framework.urlpatterns import format_suffix_patterns
from .views import talk


urls = patterns(
    'api.views',

    (r'^$', 'api_root'),

    url(r'^talks/(?P<pk>[0-9]+)$',
        talk.TalkDetailAPI.as_view(), name='talk_api_detail'),
)


urlpatterns = patterns('',
    (r'^', include(urls, namespace='api')),
)

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

events/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, patterns, url
from django.contrib import admin

from events.views import event, series


urls = patterns('events.views',

    url(r'^(?P<slug>[\w-]+)$',
        event.DetailView.as_view(), name='event_detail'),

    url(r'^$',
        event.ListView.as_view(), name='event_list'),

    url(r'^series$',
        series.ListView.as_view(), name='series_list'),
    url(r'^series/(?P<slug>[\w-]+)$',
        series.DetailView.as_view(), name='series_detail'),
)

urlpatterns = patterns(
    '', (r'^', include(urls, namespace='events')),
)

lore/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, patterns, url
from .views import talk, speaker


urls = patterns('lore.views',

    url(r'^$',
        talk.ListView.as_view(), name='talk_list'),

    url(r'^(?P<event_slug>[\w-]+)/(?P<slug>[\w-]+)$',
        talk.DetailView.as_view(), name='talk_detail'),
    url(r'^(?P<slug>[\w-]+)$',
        talk.DetailView.as_view(), name='talk_detail'),

    url(r'^speaker$',
        speaker.ListView.as_view(), name='speaker_list'),
    url(r'^speaker/(?P<slug>[\w-]+)/$',
        speaker.DetailView.as_view(), name='speaker_detail'),
)

urlpatterns = patterns(
    '', (r'^', include(urls, namespace='talks')),
)

project/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from lore.views import HomePageView


urlpatterns = patterns(
    '',

    # Home
    url(r'^$', HomePageView.as_view(), name='home'),

    # Talks
    (r'^talks/', include('lore.urls')),

    # Events
    (r'^events/', include('events.urls')),

    # Content
    (r'^content/', include('contents.urls')),

    # API
    (r'^api/', include('api.urls')),

    # Django Admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    # Only serve media files if in a development environment
    from django.conf.urls.static import static
    from django.views.generic import TemplateView
    MEDIA_ROOT = getattr(settings, 'MEDIA_ROOT')
    MEDIA_URL = getattr(settings, 'MEDIA_URL').lstrip('/')

    urlpatterns = urlpatterns + patterns('',
        (r'^errors/404$', TemplateView.as_view(template_name='404.html')),
        (r'^errors/500$', TemplateView.as_view(template_name='500.html')),
        # (r'^%(media_url)s(?P<path>.*)$' %(
        #   {'media_url': re.escape(MEDIA_URL)}),
        #   'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lore/models.py
# -*- coding: utf-8 -*-
import reversion
import requests
from bs4 import BeautifulSoup
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from . import querysets


class Category(models.Model):
    name = models.CharField(_('Title'), max_length=256, null=True, blank=True)
    colour = models.CharField(_('Color'), max_length=7, null=True, blank=True,
                              help_text = "Arbitrary colour for presentation")
    slug = models.SlugField(max_length=64)

    class Meta(object):
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

reversion.register(Category)


class Talk(models.Model):
    is_live = models.BooleanField(_("Live"), default=True)
    event = models.ForeignKey('events.Event', null=True, blank=True)
    speakers = models.ManyToManyField('lore.Speaker', null=True, blank=True)
    slug = models.SlugField(max_length=64)
    view_count = models.IntegerField(_('View count'), null=True, blank=True)


    categories = models.ManyToManyField('lore.Category', null=True, blank=True,
                                        help_text="Curated and official 'categorisation' eg.: ORM; Optimization.")

    date_delivered = models.DateTimeField(_('Date delivered'),
                                          null=True, blank=True,
                                          help_text="The date the talk was actually given/delivered/presented.")

    """ Detail from conference website """
    title = models.CharField(_('Title'), max_length=256, null=True, blank=True)
    abstract = models.TextField(_('Abstract'), null=True, blank=True)
    speaker_bio = models.TextField(_('Speaker bio'), null=True, blank=True)
    conference_url = models.URLField(_('Conference url'), null=True, blank=True)
    language = models.TextField(_('Language'), null=True, blank=True)

    # """ Detail from PyVideo """
    pyvideo_pk = models.IntegerField(_('PyVideo pk'), unique=True,
                                     null=True, blank=True)
    pyvideo_title = models.TextField(_('PyVideo title'), max_length=256,
                                     null=True, blank=True)
    pyvideo_summary = models.TextField(_('PyVideo summary'),
                                       null=True, blank=True)
    pyvideo_content = models.TextField(_('PyVideo content'),
                                       null=True, blank=True)
    pyvideo_tags = models.TextField(_('PyVideo tags'),
                                    null=True, blank=True)
    pyvideo_source_url = models.URLField(_('PyVideo source url'),
                                        null=True, blank=True)
    pyvideo_video_url = models.URLField(_('PyVideo hosted url'),
                                        null=True, blank=True)
    pyvideo_copyright = models.CharField(_('PyVideo copyright'), max_length=256,
                                         null=True, blank=True)

    # """ Detail from Youtube """
    youtube_id = models.CharField(_('Youtube id'), max_length=32, unique=True,
                                  null=True, blank=True)
    youtube_channel_id = models.CharField(_('Youtube channel id'),
                                          max_length=32, null=True, blank=True)
    youtube_title = models.TextField(_('Youtube title'), max_length=256,
                                     null=True, blank=True)
    youtube_summary = models.TextField(_('Youtube summary'),
                                       null=True, blank=True)
    youtube_content = models.TextField(_('Youtube content'),
                                       null=True, blank=True)
    youtube_views = models.IntegerField(_('Youtube views'),
                                        null=True, blank=True)
    youtube_likes = models.IntegerField(_('Youtube likes'),
                                        null=True, blank=True)
    youtube_duration = models.IntegerField(_('Youtube duration'),
                                        null=True, blank=True)
    youtube_thumbnail = models.URLField(_('Youtube thumbnail'),
                                        null=True, blank=True)
    youtube_copyright = models.CharField(_('Youtube copyright'), max_length=256,
                                         null=True, blank=True)

    objects = querysets.TalkManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('talks:talk_detail', kwargs={'slug': self.slug})

reversion.register(Talk)


class Speaker(models.Model):
    """ There should nearly certainly should be a separate module for speakers.

    But not looking to replace any existing resources out there, just point
    to them.

    BEWARE: There is a pending problem for people who have identical names.

    This can be worked around by using the 2 other external points of reference:
    * djangpeople username
    * pyvideo pk

    @@ TD: perhaps could use github account name eventually as all django
    contributors are now actually required to have such a thing.
    """
    full_name = models.CharField(_('Full name'), max_length=128)
    prenom = models.CharField(_('Prenom'), max_length=64, blank=True, null=True,
                              help_text="Name for casual reference.")
    slug = models.SlugField(max_length=64, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)

    people = models.CharField(_('Django people username'), max_length=30,
                              blank=True, null=True)
    people_photo = models.URLField(_('Django people gravatar'),
                                   blank=True, null=True)
    people_finding = models.TextField(_('Django people details'),
                                      blank=True, null=True)

    pyvideo_pk = models.IntegerField(_('PyVideo pk'), blank=True, null=True,
                                     help_text="ID number used by PyVideo")

    github = models.CharField(_('Github username'), max_length=64,
                              blank=True, null=True)

    class Meta(object):
        ordering = ['full_name']

    def __str__(self):
        if self.people:
            return "{0} ({1})".format(self.full_name, self.people)
        return self.full_name

    def get_absolute_url(self):
        return reverse('talks:speaker_detail', kwargs={'slug': self.slug})

    def get_people_url(self, username=None):
        url = 'https://people.djangoproject.com/{0}'
        if username:
            return url.format(username)
        elif self.people:
            return url.format(self.people)
        return False

    def get_pyvideo_url(self, pk=None):
        url = 'http://pyvideo.org/speaker/{0}/'
        if pk:
            return url.format(pk)
        elif self.pyvideo_pk:
            return url.format(self.pyvideo_pk)
        return False

    def get_existing_speaker_by_full_name(self, full_name):
        speakers_names = [name.lower() for name in Speaker.objects.all().values_list('full_name', flat=True)]
        if full_name in speakers_names:
            speakers = Speaker.objects.filter(full_name__istartswith=full_name)
            if len(speakers) == 1:
                return speakers[0]
            elif len(speakers) == 0:
                return False
            elif len(speakers) > 1:
                raise Exception("{0} results found!".format(len(speakers)))

    def fetch_pyvideo_pk(self):
        """Connect to PyVideo website and scrape (or try to) PyVideo PK.
        """
        url = 'http://pyvideo.org/search?models=videos.video&q={0}'.format(self.full_name.replace(" ", "+"))
        soup = BeautifulSoup(requests.get(url).content).findAll("a")
        if soup:
            for link in soup:
                if link.string == self.full_name:
                    self.pyvideo_pk = link.get('href').split('/')[2]
                    self.save()
                    return self.pyvideo_pk
        self.pyvideo_pk = None
        self.save()
        return None

    def get_existing_speaker_by_people(self, people_username):
        if people_username in Speaker.objects.all().values_list('people'):
            return Speaker.objects.get(people=people_username)
        else:
            return False

    def fetch_full_name_from_people(self):
        """ Connects to Django People website and searches and scrapes
        for people details if nobody by ``full_name`` currently exists.

        Searches for ``full_name`` and then adds ``people`` username to object.

        @@ TD: This method needs some work still.
        """
        url = 'https://people.djangoproject.com/search/?q={0}'.format(self.full_name.replace(" ", "+"))
        request = requests.get(url)
        soup = BeautifulSoup(request.content)
        vcards = soup.findAll("li", { "class" : "vcard" })
        if len(vcards) == 1:
            for vcard in soup.findAll("li", { "class" : "vcard" }):
                people_username = vcard.findAll("a", { "class" : "url fn n" })[0].attrs['href'].strip("/")
                if self.get_existing_speaker_by_people(people_username):
                    self = self.get_existing_speaker_by_people(people_username)
                self.people = people_username
                self.photo = soup.findAll("img", { "class" : "main photo" })[0].attrs['src']
                self.prenom = soup.findAll("span", { "class" : "given-name" })[0].renderContents()
                self.save()
        elif len(vcards) == 0:
            return False
        elif len(vcards) > 1:
            raise Exception("{0} results found! No records created."
                            "".format(len(vcards)))

    def fetch_people_details(self, people):
        """Connect to Django People website and scrape people details.
        """
        request = requests.get(self.get_people_url())
        soup = BeautifulSoup(request.content)
        try:

lore/forms/speaker.py
from django import forms
from ..models import Speaker


class SpeakerForm(forms.ModelForm):

    class Meta(object):
        model = Speaker

lore/forms/talk.py
from django import forms
from ..models import Talk


class TalkForm(forms.ModelForm):

    class Meta(object):
        model = Talk

lore/views/speaker.py
# -*- coding: utf-8 -*-
from django.views import generic
from ..models import Speaker


class QuerySetMixin(object):

    model = Speaker


class DetailView(QuerySetMixin, generic.DetailView):

    pass


class ListView(QuerySetMixin, generic.ListView):

    pass

lore/views/talk.py
# -*- coding: utf-8 -*-
from django.views import generic
from ..models import Talk


class QuerySetMixin(object):

    model = Talk


class DetailView(QuerySetMixin, generic.DetailView):

    pass


class ListView(QuerySetMixin, generic.ListView):

    pass

templates/lore/_detail.html
{# @@ TODO work out video fallback heirarchy #}
{% if talk.pyvideo_source_url %}<div>Video link: <a href="{{talk.pyvideo_source_url}}" target="_blank">{{talk.pyvideo_source_url}}</a></div>{% endif %}
{# {% if talk.youtube_id %}<div>{{talk.youtube_id}}</div>{% endif %} #}

<!-- Portfolio Item Row -->
<div class="row">

  <div class="col-md-5">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <a href="{{talk.pyvideo_source_url}}" target="_blank">
            <img class="img-responsive" src="{% if talk.youtube_thumbnail %}{{talk.youtube_thumbnail}}{% endif %}" alt="">
          </a>
        </div>
      </div>

    </div>
  </div>

  <div class="col-md-7">

    <h3>Project Details</h3>
    Speaker{{ talk.speakers.all|pluralize }}: {{ talk.speakers.all|join:", " }}

      {% if talk.conference_url %}<div>{{talk.conference_url}}</div>{% endif %}
      {% if talk.youtube_channel_id %}<div>{{talk.youtube_channel_id}}</div>{% endif %}
      {% if talk.youtube_views %}<div>Youtube views: {{talk.youtube_views}}</div>{% endif %}
      {% if talk.youtube_likes %}<div>Youtube likes: {{talk.youtube_likes}}</div>{% endif %}
      {% if talk.youtube_duration %}<div>Duration: {{talk.youtube_duration}}</div>{% endif %}
      {% if talk.youtube_copyright %}<div>Copyright: {{talk.youtube_copyright}}</div>{% endif %}
      {% if talk.language %}<div>Language: {{talk.language}}</div>{% endif %}


      {# @@ TODO sort out tags #}
      {# {% if talk.pyvideo_tags %}<div>{{talk.pyvideo_tags}}</div>{% endif %} #}
      {# {% if talk.view_count %}<div>{{talk.view_count}}</div>{% endif %} #}


{# conference details #}

  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h3>Project Description</h3>
    {% if talk.abstract %}{{talk.abstract}}{% endif %}
    {% if talk.pyvideo_summary %}{{talk.pyvideo_summary}}{% endif %}
    {% if talk.pyvideo_content %}{{talk.pyvideo_content}}{% endif %}

{# @@ TODO fallback heirarchy #}
{% comment %}
{% if talk.title %}{{talk.title}}{% endif %}
{% if talk.pyvideo_title %}{{talk.pyvideo_title}}{% endif %}
{% if talk.youtube_title %}{{talk.youtube_title}}{% endif %}
{% if talk.youtube_summary %}{{talk.youtube_summary}}{% endif %}
{% if talk.youtube_content %}{{talk.youtube_content}}{% endif %}
{% endcomment %}

  </div>
</div>
<!-- /.row -->

templates/lore/_list-list.html
<h2>List</h2>
{# @@ TODO Add relevant header #}

<table id="results" class="table table-striped table-hover table-bordered">

  {% for talk in object_list %}

  <tr class="media">
    <td class="col-lg-2 col-md-2">
          <a href="{{talk.pyvideo_source_url}}" target="_blank">
            <img class="img-responsive" src="{% if talk.youtube_thumbnail %}{{talk.youtube_thumbnail}}{% endif %}" alt="">
          </a>
    </td>

    <td class="media-body">

      <h4 class="media-heading">
        <a href="{% url "talks:talk_detail" slug=talk.slug %}">{{talk.title}}
          {% if talk.date_delivered %}<br><small>{{talk.date_delivered|date:"j-M-Y"}}</small>{% endif %}
        </a>
      </h4>

      {% if talk.pyvideo_source_url %}
      {# @@ TODO video link #}
      <div>Video link: <a href="{{talk.pyvideo_source_url}}" target="_blank">{{talk.pyvideo_source_url}}</a></div>{% endif %}

      {% if talk.event %}
      {# @@ TODO event link #}
      <div><a href="{{talk.event.get_absolute_url}}">{{talk.event}}</a></div>{% endif %}

      {% comment %}
      {% if talk.abstract %}{{talk.abstract}}{% endif %}
      {% if talk.speaker_bio %}{{talk.speaker_bio}}{% endif %}
      {% if talk.conference_url %}{{talk.conference_url}}{% endif %}
      {% endcomment %}
    </td>
  </tr>

  {% endfor %}

</table>

templates/lore/base.html
{% extends 'base.html' %}

templates/lore/talk_detail.html
{% extends 'lore/base.html' %}

{% block title %}
{{ talk }}
<div>
  <small>
      {# @@ TODO event link #}
      <a href="{% url "events:event_detail" slug=talk.event.slug %}">{{ talk.event }}</a>
      {% if talk.date_delivered %}({{talk.date_delivered|date:"j-M-Y"}}){% endif %}
  </small>
  {# @@ TODO CATEGORY #} {% if talk.categories.all %}{{talk.categories.all|join:", "}}{% endif %}
</div>
{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'talks:talk_list' %}">Talks</a></li>
{% endblock %}

{% block content %}

{% include 'lore/_detail.html' %}

{% endblock %}

templates/lore/talk_list.html
{% extends 'lore/base.html' %}

{% block title %}
List of Talks
{% endblock %}

{% block breadcrumbs %}
<li><a href="index.html">Talks</a></li>
{% endblock %}

{% block content %}

    {% include 'lore/_list-list.html' %}

{% endblock %}