api/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.conf.urls import include, patterns, url
from rest_framework.urlpatterns import format_suffix_patterns
from .views import talk


urls = patterns(
    'api.views',

    (r'^$', 'api_root'),

    url(r'^talks/(?P<pk>[0-9]+)$',
        talk.TalkDetailAPI.as_view(), name='talk_api_detail'),
)


urlpatterns = patterns('',
    (r'^', include(urls, namespace='api')),
)

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

events/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, patterns, url
from django.contrib import admin

from events.views import event, series


urls = patterns('events.views',

    url(r'^(?P<slug>[\w-]+)$',
        event.DetailView.as_view(), name='event_detail'),

    url(r'^$',
        event.ListView.as_view(), name='event_list'),

    url(r'^series$',
        series.ListView.as_view(), name='series_list'),
    url(r'^series/(?P<slug>[\w-]+)$',
        series.DetailView.as_view(), name='series_detail'),
)

urlpatterns = patterns(
    '', (r'^', include(urls, namespace='events')),
)

project/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from lore.views import HomePageView


urlpatterns = patterns(
    '',

    # Home
    url(r'^$', HomePageView.as_view(), name='home'),

    # Talks
    (r'^talks/', include('lore.urls')),

    # Events
    (r'^events/', include('events.urls')),

    # Content
    (r'^content/', include('contents.urls')),

    # API
    (r'^api/', include('api.urls')),

    # Django Admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    # Only serve media files if in a development environment
    from django.conf.urls.static import static
    from django.views.generic import TemplateView
    MEDIA_ROOT = getattr(settings, 'MEDIA_ROOT')
    MEDIA_URL = getattr(settings, 'MEDIA_URL').lstrip('/')

    urlpatterns = urlpatterns + patterns('',
        (r'^errors/404$', TemplateView.as_view(template_name='404.html')),
        (r'^errors/500$', TemplateView.as_view(template_name='500.html')),
        # (r'^%(media_url)s(?P<path>.*)$' %(
        #   {'media_url': re.escape(MEDIA_URL)}),
        #   'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/_form.html
{% load crispy_forms_tags %}
{% crispy form %}

templates/_nav.html
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

    {# <!-- Brand and toggle get grouped for better mobile display --> #}
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">History</a>
    </div>

    {# <!-- Collect the nav links, forms, and other content for toggling --> #}
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Events <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url "events:event_list" %}">events</a></li>
          </ul>
        </li>
        <li><a href="about.html">About</a></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Django History, Homework, Catch-up</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/project.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block extrahead %}{% endblock %}
</head>

<body>

{% include '_nav.html' %}

{% block body %}

    {# <!-- Page Content --> #}
    <div class="container">

        {% block breadcrumb %}
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{% block title %}{% endblock %}</h1>
                <ol class="breadcrumb">
                    {% block breadcrumbs %}
                    {% endblock %}
                </ol>
            </div>
        </div>
        <!-- /.row -->
        {% endblock %}

        {% block content %}{% endblock %}

        <hr>

{% endblock body %}

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                  <p>
                    <a href="https://www.djangoproject.com/foundation/"> Django Software Foundation</a> unless otherwise noted. Django is a
                    <a href="https://www.djangoproject.com/trademarks/">registered trademark</a> of the Django Software Foundation.
                  </p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
    {# <!-- Page Content end --> #}

    <!-- jQuery Version 1.11.0 -->
    <script src="/static/js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
      $('.carousel').carousel({
      interval: 3000 //changes the speed
      })
    </script>

    {% block scripts %}{% endblock %}

</body>

</html>

templates/home.html
{% extends 'base.html'%}


{% block title %}
{{ talk }}
<div> &nbsp; <small>{{ talk.event }} {% if talk.date_delivered %}({{talk.date_delivered|date:"j-M-Y"}}){% endif %}</small>
  {# @@ TODO CATEGORY #} {% if talk.categories.all %}{{talk.categories.all|join:", "}}{% endif %}
</div>
{% endblock %}


{% block body %}

    <!-- Header Carousel -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">

            <div class="item active">

              <div class="container">
                <div class="row">
                  <div class="col-lg-12">
                    <h2 class="page-header">Featured:</h2>
                  </div>
                </div>

                {% include 'lore/_detail.html' %}
              </div>

            </div>

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>

<hr>


    <div class="container">
        <!-- Service Tabs -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Service Tabs</h2>
            </div>
            <div class="col-lg-12">

                <ul id="myTab" class="nav nav-tabs nav-justified">
                    <li class="active"><a href="#one" data-toggle="tab"><i class="fa fa-tree"></i> Popular</a></li>
                    <li class=""><a href="#two" data-toggle="tab"><i class="fa fa-car"></i> Recent</a></li>
                    <li class=""><a href="#three" data-toggle="tab"><i class="fa fa-support"></i> Unwatched</a></li>
                </ul>

                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade active in" id="one">

    {% include 'lore/_list-list.html' %}

                    </div>
                    <div class="tab-pane fade" id="two">

    {% include 'lore/_list-list.html' %}

                    </div>
                    <div class="tab-pane fade" id="three">

    {% include 'lore/_list-list.html' %}

                    </div>

                </div>

            </div>
        </div>
    </div>

{% endblock %}


{% comment %}
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Django History</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 col-md-6">
        <a href="portfolio-item.html">
          <img class="img-responsive img-hover" src="http://placehold.it/700x300" alt="">
        </a>
      </div>
      <div class="col-lg-6 col-md-6">
        <h3>Project One</h3>
        <h4>Subheading</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
        <a class="btn btn-primary" href="portfolio-item.html">View Project</i></a>
</div>
</div>

{% endcomment %}